[global]

showWarningOnDirectExecution = false

[logger]
level = "debug"
messageFormat = "%(asctime)s - [%(levelname)s] - %(message)s"



[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501
