
[theme]
primaryColor = "#00D8FF"  # Inspired by the light blue in the logo
backgroundColor = "#F7F8FA"  # A light background similar to the logo background
secondaryBackgroundColor = "#FFFFFF"  # White, to maintain a clean look
textColor = "#333333"  # Dark grey for text, similar to the "Experiment your way" text
font = "sans serif"

